server:
  port: 8080

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/product-utility

logging:
  file:
    name: logs/product.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"